# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:
  
jobs:
  build:
    environment: predeployment
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: mkdir -p ./test/.homebridge/ && touch ./test/.homebridge/config.json
    - name: json-to-file
      uses: devops-actions/json-to-file@v1.0.0
      with:
        json: ${{ secrets.CONFIG_JSON }}
        filename: ./test/.homebridge/config.json
    - run: npm ci
    - run: cat ./test/.homebridge/config.json
